// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Persistence.Context;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(NakliyatDbContext))]
    partial class NakliyatDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserRole")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserSurname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11d8550c-c548-4cbc-8519-4ff82dded7bd"),
                            CreatedDate = new DateTime(2023, 9, 8, 15, 42, 4, 924, DateTimeKind.Utc).AddTicks(1035),
                            Email = "user1@gmail.com",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserName = "User 1",
                            UserRole = "Company",
                            UserSurname = "Surname"
                        },
                        new
                        {
                            Id = new Guid("bc70c1de-0ae8-44ee-990a-8b2ece934063"),
                            CreatedDate = new DateTime(2023, 9, 8, 15, 42, 4, 924, DateTimeKind.Utc).AddTicks(1040),
                            Email = "user2@gmail.com",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserName = "User 2",
                            UserRole = "Customer",
                            UserSurname = "Surname"
                        },
                        new
                        {
                            Id = new Guid("a444452c-b0a7-4798-8c46-6775d250dcd4"),
                            CreatedDate = new DateTime(2023, 9, 8, 15, 42, 4, 924, DateTimeKind.Utc).AddTicks(1042),
                            Email = "user3@gmail.com",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserName = "User 3",
                            UserRole = "Customer",
                            UserSurname = "Surname"
                        },
                        new
                        {
                            Id = new Guid("7fd826e9-cc6e-417c-9fb4-2804653645f7"),
                            CreatedDate = new DateTime(2023, 9, 8, 15, 42, 4, 924, DateTimeKind.Utc).AddTicks(1046),
                            Email = "user4@gmail.com",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserName = "User 4",
                            UserRole = "Company",
                            UserSurname = "Surname"
                        },
                        new
                        {
                            Id = new Guid("155635fb-2711-4be9-b76b-c2c07be8fae1"),
                            CreatedDate = new DateTime(2023, 9, 8, 15, 42, 4, 924, DateTimeKind.Utc).AddTicks(1049),
                            Email = "user5@gmail.com",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserName = "User 5",
                            UserRole = "Customer",
                            UserSurname = "Surname"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
